//APP MODULE
export const SET_APP_STATUS = "SET_APP_STATUS";
export const SET_SIDEBAR = "SET_SIDEBAR";
export const SET_PRINT = "SET_PRINT";
export const SET_LOADING = "SET_LOADING";
export const SET_EXPORT_JSON = "SET_EXPORT_JSON";

//MAP MODULE
export const SET_BASELAYER_VISIBILITY = "SET_BASELAYER_VISIBILITY";
export const SET_LAYER_VISIBILITY = "SET_LAYER_VISIBILITY";
export const SET_MULTI_INFO = "SET_MULTI_INFO";
export const SET_DRAW_TYPE = "SET_DRAW_TYPE";
export const SET_SELECTED_FEATURE = "SET_SELECTED_FEATURE";
export const SET_ACTIVE_TREE_ITEM = "SET_ACTIVE_TREE_ITEM";
export const SET_ACTIVE_LAYER = "SET_ACTIVE_LAYER";
export const SET_MEASURE_OUTPUT = "SET_MEASURE_OUTPUT";
